---
name: "Dependency App - JavaScript action"

"on":
   workflow_dispatch:

   schedule:
      - cron: "0 5 * * 6"

env:
   ACTION_FILENAME: "action.yml"

permissions:
   contents: read
   pull-requests: read

jobs:
   get-lts:
      name: "Get all available versions"
      runs-on: ubuntu-latest

      steps:
         - name: Node LTS versions
           id: get
           uses: msimerson/node-lts-versions@2c529228898a89f07e71d5ed39f7034a6fbe4df8  # v1.7.4

         - name: Output informations
           run: |
              echo active: ${{ steps.get.outputs.active }}
              echo maintenance: ${{ steps.get.outputs.maintenance }}
              echo "lts: ${{ steps.get.outputs.lts }}"
              echo current: ${{ steps.get.outputs.current }}
              echo min: ${{ steps.get.outputs.min }}

      outputs:
         # active: ${{ steps.get.outputs.active }}
         # maintenance: ${{ steps.get.outputs.maintenance }}
         lts: ${{ steps.get.outputs.lts }}
         current: ${{ steps.get.outputs.active }}
         # min: ${{ steps.get.outputs.min }}


   check-version:
      name: "Check the version"
      runs-on: ubuntu-latest
      needs: get-lts

      permissions:
         contents: write
         pull-requests: write

      strategy:
         matrix:
            # os: [ubuntu-latest, windows-latest, macos-latest]
            nodeversion: ${{ fromJson(needs.get-lts.outputs.lts) }}
         fail-fast: false

      steps:
         - name: "Debug output"
           run: |
              echo "node${NODEVER}"
           env:
              NODEVER: ${{ matrix.nodeversion }}

         - name: Generate app token
           uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
           id: generate-token
           with:
              app-id: ${{ secrets.APP_2106269_ID }}
              private-key: ${{ secrets.APP_2106269_PRIVATE_KEY }}

         - name: Create a new branch
           uses: peterjgrainger/action-create-branch@10c7d268152480ae859347db45dc69086cef1d9c  # v3.0.0
           env:
              GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
           with:
              branch: dependabot/nodejs/nodejs-${{ matrix.nodeversion }}-to-${{ fromJson(needs.get-lts.outputs.current)[0] }}

         - name: Checkout new created branch
           uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
           with:
              ref: dependabot/nodejs/nodejs-${{ matrix.nodeversion }}-to-${{ fromJson(needs.get-lts.outputs.current)[0] }}

         - name: Find and Replace
           id: hit
           uses: jacobtomlinson/gha-find-replace@f1069b438f125e5395d84d1c6fd3b559a7880cb5  # v3.0.5
           with:
              find: "node${{ matrix.nodeversion }}"
              replace: "node${{ fromJson(needs.get-lts.outputs.current)[0] }}"
              include: ${{ env.ACTION_FILENAME }}

         - name: Debug output
           run: |
              echo "Files: ${DEBUG}"
           env:
              DEBUG: ${{ steps.hit.outputs.modifiedFiles }}

         - name: Commit & Push changes
           if: steps.hit.outputs.modifiedFiles > 0
           uses: actions-js/push@5a7cbd780d82c0c937b5977586e641b2fd94acc5  # v1.5
           with:
              branch: dependabot/nodejs/nodejs-${{ matrix.nodeversion }}-to-${{ fromJson(needs.get-lts.outputs.current)[0] }}
              GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
              force: true
              message: "Bump github/node.js from ${{ matrix.nodeversion }} to ${{ fromJson(needs.get-lts.outputs.current)[0] }}"

         - name: Create pull request
           if: steps.hit.outputs.modifiedFiles > 0
           id: pullrequest
           uses: devops-infra/action-pull-request@b2895bff2ff66579f6704d717a1ea75fad919e84  # v1.0.2
           with:
              GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
              source_branch: dependabot/nodejs/nodejs-${{ matrix.nodeversion }}-to-${{ fromJson(needs.get-lts.outputs.current)[0] }}
              target_branch: master
              title: "Bump github/node.js from ${{ matrix.nodeversion }} to ${{ fromJson(needs.get-lts.outputs.current)[0] }}"
              body: "Bump [github/node.js](https://docs.github.com/de/actions/reference/workflows-and-actions/metadata-syntax#runs) from ${{ matrix.nodeversion }} to ${{ fromJson(needs.get-lts.outputs.current)[0] }}."
              label: "github_actions,dependencies"

         - name: Delete previously created branch
           if: steps.hit.outputs.modifiedFiles == 0
           uses: dawidd6/action-delete-branch@d1efac9a6f7a9b408d4e8ff663a99c1fbac17b3f  # v3.1.0
           with:
              GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
              branches: dependabot/nodejs/nodejs-${{ matrix.nodeversion }}-to-${{ fromJson(needs.get-lts.outputs.current)[0] }}
